[changelog]
header = """
## What's Changed
"""
body = """
{% if commits | length == 0 %}
- No notable changes in this release.
{% else %}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {% if commit.scope %}**{{ commit.scope }}:** {% endif %}{{ commit.message }}
{% endfor %}
{% endfor %}
{% endif %}

### Full Changelog
{% for commit in commits %}
- {{ commit.id }} {{ commit.message }}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
protect_breaking_commits = true
filter_commits = false
topo_order = false
sort_commits = "oldest"

commit_parsers = [
  { message = "^feat", group = "New Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Refactors" },
  { message = "^docs", group = "Documentation" },
  { message = "^test", group = "Tests" },
  { message = "^build", group = "Build" },
  { message = "^ci", group = "CI" },
  { message = "^chore", group = "Chores" },
  { message = "^revert", group = "Reverts" },
  { message = "^Merge", skip = true },
  { message = "^Bump", group = "Chores" },
  { message = "^.*", group = "Other Changes" },
]
